export function buildPostmanCollection({
  project,
  endpoints,
  baseUrl,
  token = '',
  liveResponses = new Map(),
}) {
  const collection = {
    info: {
      name: project?.title || 'API Documentation',
      description: project?.description || 'Generated by htmltpostman CLI with rich documentation and live responses',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    variable: [
      {
        key: 'base_url',
        value: baseUrl || 'http://localhost',
        type: 'string',
      },
      {
        key: 'token',
        value: token || '',
        type: 'string',
      },
    ],
    item: [],
  };

  // Group endpoints by groupTitle or group
  const grouped = new Map();
  for (const ep of endpoints) {
    const groupName = ep.groupTitle || ep.group || 'General';
    if (!grouped.has(groupName)) {
      grouped.set(groupName, []);
    }
    grouped.get(groupName).push(ep);
  }

  for (const [groupName, eps] of grouped.entries()) {
    const folder = {
      name: groupName,
      item: eps.map(ep => buildPostmanItem(ep, liveResponses)),
    };
    collection.item.push(folder);
  }

  return collection;
}

function buildPostmanItem(endpoint, liveResponses) {
  const rawUrl = endpoint.url.startsWith('/') ? endpoint.url : `/${endpoint.url}`;
  const fullRawUrl = `{{base_url}}${rawUrl}`;

  // Extract path segments
  const pathSegments = rawUrl
    .split('?')[0]
    .split('/')
    .filter(Boolean);

  // Extract Path Variables
  const pathVariables = [];
  for (const seg of pathSegments) {
    if (seg.startsWith(':')) {
      const varKey = seg.substring(1);
      const matchedParam = (endpoint.params || []).find(p => p.field === varKey);
      pathVariables.push({
        key: varKey,
        value: matchedParam?.defaultValue || '',
        description: matchedParam?.description || `Path parameter ${varKey}`,
      });
    }
  }

  // Extract Query Parameters
  const queryParams = [];
  if (Array.isArray(endpoint.params)) {
    for (const p of endpoint.params) {
      if (!p.field.startsWith(':') && !pathSegments.includes(`:${p.field}`)) {
        queryParams.push({
          key: p.field,
          value: p.defaultValue || (p.allowedValues && p.allowedValues.length > 0 ? p.allowedValues[0].replace(/^"|"$/g, '') : ''),
          description: p.description || '',
          disabled: !!p.optional && !p.defaultValue,
        });
      }
    }
  }

  // Headers
  const headers = [];
  headers.push({
    key: 'Accept',
    value: 'application/json',
  });

  const isUnauthenticated = endpoint.permission && /unauthenticated|none/i.test(endpoint.permission);
  if (!isUnauthenticated) {
    headers.push({
      key: 'Authorization',
      value: 'Bearer {{token}}',
    });
  }

  if (Array.isArray(endpoint.headers)) {
    for (const h of endpoint.headers) {
      if (h.key.toLowerCase() !== 'accept' && h.key.toLowerCase() !== 'authorization') {
        headers.push({
          key: h.key,
          value: h.value,
          description: h.description,
        });
      }
    }
  }

  // Body Construction with Realistic Defaults
  let body = undefined;
  let bodyObj = {};
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(endpoint.method)) {
    if (Array.isArray(endpoint.body) && endpoint.body.length > 0) {
      for (const b of endpoint.body) {
        bodyObj[b.field] = resolveSampleValue(b);
      }
    }

    if (Object.keys(bodyObj).length > 0) {
      headers.push({
        key: 'Content-Type',
        value: 'application/json',
      });

      body = {
        mode: 'raw',
        raw: JSON.stringify(bodyObj, null, 2),
        options: {
          raw: {
            language: 'json',
          },
        },
      };
    }
  }

  // Extract Live Response if available
  let liveRespItem = null;
  if (liveResponses.has(endpoint.name)) {
    const list = liveResponses.get(endpoint.name);
    if (list && list.length > 0) {
      liveRespItem = list[0];
    }
  }

  // Generate Rich Markdown Documentation for Postman Docs Tab
  const markdownDocs = generateMarkdownDocumentation(
    endpoint,
    pathVariables,
    queryParams,
    headers,
    bodyObj,
    liveRespItem
  );

  const request = {
    method: endpoint.method,
    header: headers,
    url: {
      raw: fullRawUrl,
      host: ['{{base_url}}'],
      path: pathSegments,
      query: queryParams.length > 0 ? queryParams : undefined,
      variable: pathVariables.length > 0 ? pathVariables : undefined,
    },
    description: markdownDocs,
    body,
  };

  // Saved Responses (Examples)
  const responses = [];

  // 1. Live Captured Response (if executed)
  if (liveRespItem) {
    responses.push(liveRespItem);
  }

  // 2. Documentation Success Response (from ApiDoc)
  if (endpoint.exampleResponse) {
    const parsedDocExample = parseDocExample(endpoint.raw?.success?.examples?.[0]?.content, endpoint.exampleResponse);
    responses.push({
      name: `${parsedDocExample.code} ${parsedDocExample.status} - Documentation Example`,
      originalRequest: {
        method: endpoint.method,
        header: headers,
        url: {
          raw: fullRawUrl,
          host: ['{{base_url}}'],
          path: pathSegments,
        },
        body,
      },
      status: parsedDocExample.status,
      code: parsedDocExample.code,
      _postman_previewlanguage: 'json',
      header: [
        { key: 'Content-Type', value: 'application/json' },
      ],
      cookie: [],
      body: parsedDocExample.body,
    });
  }

  // 3. Standard 401 Unauthorized Error Example (if endpoint requires auth)
  if (!isUnauthenticated) {
    responses.push({
      name: '401 Unauthorized - Error Example',
      originalRequest: {
        method: endpoint.method,
        header: headers,
        url: {
          raw: fullRawUrl,
          host: ['{{base_url}}'],
          path: pathSegments,
        },
        body,
      },
      status: 'Unauthorized',
      code: 401,
      _postman_previewlanguage: 'json',
      header: [
        { key: 'Content-Type', value: 'application/json' },
      ],
      cookie: [],
      body: JSON.stringify({ message: 'Unauthenticated.' }, null, 2),
    });
  }

  // 4. Standard 422 Validation Error Example (if endpoint has request body)
  if (Object.keys(bodyObj).length > 0) {
    const errorDetails = {};
    for (const key of Object.keys(bodyObj).slice(0, 3)) {
      errorDetails[key] = [`The ${key} field is required.`];
    }
    responses.push({
      name: '422 Unprocessable Entity - Validation Error',
      originalRequest: {
        method: endpoint.method,
        header: headers,
        url: {
          raw: fullRawUrl,
          host: ['{{base_url}}'],
          path: pathSegments,
        },
        body,
      },
      status: 'Unprocessable Entity',
      code: 422,
      _postman_previewlanguage: 'json',
      header: [
        { key: 'Content-Type', value: 'application/json' },
      ],
      cookie: [],
      body: JSON.stringify({
        message: 'The given data was invalid.',
        errors: errorDetails,
      }, null, 2),
    });
  }

  return {
    name: endpoint.title || endpoint.name,
    request,
    response: responses,
  };
}

function resolveSampleValue(field) {
  if (field.defaultValue !== undefined && field.defaultValue !== null && field.defaultValue !== '') {
    const val = field.defaultValue.trim();
    if (val.toLowerCase() === 'true') return true;
    if (val.toLowerCase() === 'false') return false;
    if (val.toLowerCase() === 'null') return null;
    if (/^\d+$/.test(val)) return parseInt(val, 10);
    if (/^\d+\.\d+$/.test(val)) return parseFloat(val);
    return val.replace(/^"|"$/g, '');
  }

  if (Array.isArray(field.allowedValues) && field.allowedValues.length > 0) {
    return field.allowedValues[0].replace(/^"|"$/g, '');
  }

  const name = field.field.toLowerCase();
  const type = (field.type || '').toLowerCase();

  // Smart heuristic defaults based on field name
  if (name.includes('email')) return 'admin@admin.com';
  if (name.includes('password')) return 'admin';
  if (name.includes('phone')) return '0901234567';
  if (name.includes('domain')) return 'example.com';
  if (name.includes('url') || name.includes('link')) return 'https://api.example.com';
  if (name === 'quota') return 1024;
  if (name === 'local_part') return 'info';
  if (name.includes('name') || name.includes('title')) return 'Sample Name';
  if (name.includes('description') || name.includes('content') || name.includes('note')) return 'Detailed sample description';
  if (name.includes('date') || name.includes('birthday')) return '2026-01-01';
  if (name === 'status') return 'active';
  if (name.includes('is_') || name.includes('has_') || type.includes('bool')) return true;
  if (type.includes('num') || type.includes('int') || type.includes('float')) return 1;
  if (type.includes('array')) return [];
  if (type.includes('object')) return {};

  return 'string';
}

function parseDocExample(rawContent, exampleResponse) {
  let code = 200;
  let status = 'OK';

  if (rawContent && typeof rawContent === 'string') {
    const match = rawContent.match(/HTTP\/[\d.]+\s+(\d+)\s*([^\r\n]*)/i);
    if (match) {
      code = parseInt(match[1], 10);
      status = match[2].trim() || (code === 204 ? 'No Content' : (code === 201 ? 'Created' : 'OK'));
    }
  }

  const body = typeof exampleResponse === 'object' && exampleResponse !== null
    ? JSON.stringify(exampleResponse, null, 2)
    : String(exampleResponse || '{}');

  return { code, status, body };
}

function generateMarkdownDocumentation(
  endpoint,
  pathVariables,
  queryParams,
  headers,
  bodyObj,
  liveRespItem
) {
  const parts = [];

  // 1. Header & Title
  parts.push(`## ${endpoint.title || endpoint.name}`);
  parts.push(`> \`${endpoint.method}\` \`${endpoint.url}\`\n`);

  // 2. Overview / Description
  if (endpoint.description && endpoint.description.trim()) {
    parts.push(`### 📝 Mô tả`);
    parts.push(endpoint.description.trim());
    parts.push('');
  }

  // 3. Permissions & Auth
  parts.push(`### 🔒 Phân quyền & Xác thực`);
  const isPublic = endpoint.permission && /unauthenticated|none/i.test(endpoint.permission);
  parts.push(`- **Trạng thái:** ${isPublic ? '🟢 Không cần đăng nhập (Public)' : '🔴 Bắt buộc xác thực Bearer Token (Authenticated)'}`);
  if (endpoint.permission) {
    parts.push(`- **Chi tiết quyền:** \`${endpoint.permission}\``);
  }
  parts.push('');

  // 4. Request Headers Table
  if (headers && headers.length > 0) {
    parts.push(`### 📋 Request Headers`);
    parts.push(`| Header | Giá trị | Bắt buộc | Mô tả |`);
    parts.push(`| :--- | :--- | :---: | :--- |`);
    for (const h of headers) {
      const isReq = h.key.toLowerCase() === 'accept' || h.key.toLowerCase() === 'authorization' ? 'Có' : 'Không';
      parts.push(`| \`${h.key}\` | \`${h.value || '-'}\` | ${isReq} | ${h.description || '-'} |`);
    }
    parts.push('');
  }

  // 5. Path Parameters Table
  if (pathVariables && pathVariables.length > 0) {
    parts.push(`### 🎯 Path Parameters (Tham số URL)`);
    parts.push(`| Tham số | Kiểu | Bắt buộc | Mô tả |`);
    parts.push(`| :--- | :---: | :---: | :--- |`);
    for (const pv of pathVariables) {
      parts.push(`| \`:${pv.key}\` | \`String / ID\` | **Có** | ${pv.description || '-'} |`);
    }
    parts.push('');
  }

  // 6. Query Parameters Table
  if (queryParams && queryParams.length > 0) {
    parts.push(`### 🔍 Query Parameters (Tham số truy vấn)`);
    parts.push(`| Tham số | Bắt buộc | Mặc định | Mô tả |`);
    parts.push(`| :--- | :---: | :---: | :--- |`);
    for (const qp of queryParams) {
      const isReq = qp.disabled ? 'Không' : '**Có**';
      parts.push(`| \`${qp.key}\` | ${isReq} | \`${qp.value || '-'}\` | ${qp.description || '-'} |`);
    }
    parts.push('');
  }

  // 7. Request Body Table & JSON Sample
  if (Array.isArray(endpoint.body) && endpoint.body.length > 0) {
    parts.push(`### 📦 Request Body`);
    parts.push(`| Trường dữ liệu | Kiểu | Bắt buộc | Giá trị mẫu | Mô tả |`);
    parts.push(`| :--- | :---: | :---: | :--- | :--- |`);
    for (const b of endpoint.body) {
      const isReq = b.optional ? 'Không' : '**Có**';
      const sampleVal = String(bodyObj[b.field] !== undefined ? bodyObj[b.field] : '-');
      parts.push(`| \`${b.field}\` | \`${b.type || 'String'}\` | ${isReq} | \`${sampleVal}\` | ${b.description || '-'} |`);
    }
    parts.push('');

    parts.push(`#### 💡 Ví dụ Request Body (JSON)`);
    parts.push('```json');
    parts.push(JSON.stringify(bodyObj, null, 2));
    parts.push('```\n');
  }

  // 8. Response Examples Section
  parts.push(`### 🎯 Ví dụ Phản hồi (Response Examples)\n`);

  if (liveRespItem) {
    parts.push(`#### ✅ Phản hồi thực tế từ Server (${liveRespItem.code} ${liveRespItem.status})`);
    parts.push('```json');
    parts.push(liveRespItem.body || '{}');
    parts.push('```\n');
  }

  if (endpoint.exampleResponse) {
    const docParsed = parseDocExample(endpoint.raw?.success?.examples?.[0]?.content, endpoint.exampleResponse);
    parts.push(`#### 📄 Phản hồi mẫu từ Tài liệu ApiDoc (${docParsed.code} ${docParsed.status})`);
    parts.push('```json');
    parts.push(docParsed.body);
    parts.push('```\n');
  }

  return parts.join('\n');
}
